#!/bin/bash
# ------------------------------------------------------------------
# Sven Rouvinez & Yohann Meyer - SRC2PDF
#           Allow printing of assignement code
#           for Mr. Rentsch's courses at HEIG-VD.
# ------------------------------------------------------------------
#  requirements: texlive-full. 
#   (Can probably be done with only some LaTeX packages.
#    Exercice is left to the user)

VERSION=0.3.2
USAGE="Usage: src2pdf -a 'AUTHOR' path/to/file"
AUTHOR="John Doe"
DIRECTORY="convert"


while getopts ":a:vh" optname
do
   case "$optname" in
   a)
      AUTHOR="$OPTARG"
   ;;

   h)
       echo $USAGE
       exit 0;
       ;;
   v)
       echo $VERSION
       exit 0;
       ;;
   *)
      echo "false parameters"
   ;;
   esac
done


if [ ! -d "$DIRECTORY" ]; then
   mkdir $DIRECTORY
fi

for f in *.java
do
echo "
\documentclass[a4paper,9pt]{article}

\usepackage[utf8]{inputenc}
\usepackage{graphicx}
\usepackage{fancyhdr}
\usepackage[usenames,dvipsnames]{color}  %% Allow color names
\usepackage{pxfonts}
\usepackage{textcomp}

\usepackage{listings}

\usepackage{geometry}           %%larger margin to avoid unnececery line breaks
\geometry{
left=1.5in,
right=0.7in,
top=1in,
}

\pagestyle{fancy}
\setlength\headheight{26pt}


%% Path to file, just change this one 
\newcommand{\pathcodefile}{"$f"}
\cfoot{\thepage}
\renewcommand*{\ttdefault}{pcr}
\fancyheadoffset[L]{2cm}
\fancyhead[LO]{\footnotesize\textbf{"$f"}}
\fancyhead[RO]{\footnotesize\textbf{"$AUTHOR" - POO1 - HEIG-VD}}

%footer bar
\renewcommand{\footrulewidth}{0.4pt}% default is 0pt

%% The listings package will format your source code

\lstdefinestyle{customasm}{
    belowcaptionskip=1\baselineskip,
    xleftmargin=\parindent,
    language=java,
    breaklines=true, %% Wrap long lines
    basicstyle=\footnotesize\ttfamily,
    commentstyle=\itshape\color{black},
    stringstyle=\color{black},
    keywordstyle=\bfseries\color{black},
    identifierstyle=\color{black},
    inputencoding=utf8,
    extendedchars=true,
    literate=
    {á}{{\'a}}1 {é}{{\'e}}1 {í}{{\'i}}1 {ó}{{\'o}}1 {ú}{{\'u}}1
    {Á}{{\'A}}1 {É}{{\'E}}1 {Í}{{\'I}}1 {Ó}{{\'O}}1 {Ú}{{\'U}}1
    {à}{{\`a}}1 {è}{{\`e}}1 {ì}{{\`i}}1 {ò}{{\`o}}1 {ù}{{\`u}}1
    {À}{{\`A}}1 {È}{{\'E}}1 {Ì}{{\`I}}1 {Ò}{{\`O}}1 {Ù}{{\`U}}1
    {ä}{{\"a}}1 {ë}{{\"e}}1 {ï}{{\"i}}1 {ö}{{\"o}}1 {ü}{{\"u}}1
    {Ä}{{\"A}}1 {Ë}{{\"E}}1 {Ï}{{\"I}}1 {Ö}{{\"O}}1 {Ü}{{\"U}}1
    {â}{{\^a}}1 {ê}{{\^e}}1 {î}{{\^i}}1 {ô}{{\^o}}1 {û}{{\^u}}1
    {Â}{{\^A}}1 {Ê}{{\^E}}1 {Î}{{\^I}}1 {Ô}{{\^O}}1 {Û}{{\^U}}1
    {œ}{{\oe}}1 {Œ}{{\OE}}1 {æ}{{\ae}}1 {Æ}{{\AE}}1 {ß}{{\ss}}1
    {ç}{{\c c}}1 {Ç}{{\c C}}1 {ø}{{\o}}1 {å}{{\r a}}1 {Å}{{\r A}}1
    {€}{{\EUR}}1 {£}{{\pounds}}1,
    xleftmargin=-8em,
    showstringspaces=false
         }        
\begin{document}

\lstinputlisting[style=customasm]{\pathcodefile}

\end{document}" | pdflatex -output-directory=$DIRECTORY -jobname=$f
done
